version: '3.8'

services:
  tasker:
    build: .
    image: tasker:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - API_KEY=${API_KEY}
